### ISSUE TITLE
Перевірка отриманих даних edr_handler

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#12]
https://github.com/openprocurement/openprocurement.bot.identification/blob/master/openprocurement/bot/identification/databridge/edr_handler.py#L165 - https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/215395014#L199
https://github.com/openprocurement/openprocurement.bot.identification/blob/master/openprocurement/bot/identification/databridge/edr_handler.py#L83 -
https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/215395014#L207

**Comment by Krokop** [comment]
tests/edr_handler -> в строках 351,383 навмисно передаються дані іншого формату (list замість dict в одному випадку та dict замість list в іншому) для ініціювання помилок та тестування роботи строк 244-248 в databridge/edr_handler.

**Comment by kroman0** [comment]
Потрібно обробляти некоректний формат, віддаючи warning про неможливість обробити отримані дані, а не ламатись на кожній непередбачуваній ситуації.
