### ISSUE TITLE
ProxyClient не підтримує версійність проксі

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#17]
https://github.com/openprocurement/openprocurement.bot.identification/blob/master/openprocurement/bot/identification/databridge/bridge.py#L50
https://github.com/openprocurement/openprocurement.bot.identification/blob/master/openprocurement/bot/identification/client.py#L5
```
2017-04-03 12:58:50,866 - openprocurement.bot.identification.databridge.edr_handler - INFO - Error appeared while requesting to EDR. Description: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
```

**Comment by kroman0** [comment]
Потрібно ще додати proxy_version в https://github.com/openprocurement/openprocurement.bridge.buildout/blob/edr_integration/templates/bot_identification_bridge.yaml

**Comment by kroman0** [comment]
і в https://github.com/openprocurement/openprocurement.ansible.edr/blob/master/roles/bot/templates/api.cfg.j2

**Comment by IrynaPomazan** [comment]
https://github.com/openprocurement/openprocurement.bridge.buildout/pull/5 та https://github.com/openprocurement/openprocurement.ansible.edr/pull/6
