### ISSUE TITLE
Опрацювання "EDRPOU not found"

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#23]
`При негативній відповіді ЄДР API, бот має видати документ-витяг з зафіксованою негативною відповіддю`

**Comment by IrynaPomazan** [comment]
Зараз якщо едрпоу не знайдений (отримуємо пусту відповідь від  ЕДР API) в тендер завантажується файл наступного змісту: {'error': 'Couldn't find this code in EDR.'}.

**Comment by kroman0** [comment]
Наразі не завантажується - https://lb.api-sandbox.openprocurement.org/api/dev/tenders/c1a96a62ae2b48a6a51226c9eafd2d96
