### ISSUE TITLE
Дані довідки в атрибуті data

### ISSUE THREAD

**Issue by myroslav** [openprocurement/openprocurement.bot.identification#30]
Всі "корисні" дані довідки (payload) потрібно перемістити в атрибут `data` подібно до того, як інформацію віддає API та EDRproxy. Це уніфікує формат інформації та дозволить додатково в довідку включити службову інформацію, наприклад дату формування відповіді від реєстру та номери запитів в межах яких було сформовано цю довідку.

**Comment by Mexicanec** [comment]
згоден.

**Comment by kroman0** [comment]
#44

**Comment by kroman0** [comment]
@IrynaPomazan чи маєте приклад довідки на dev?
