### ISSUE TITLE
Версійність форматів довідки

### ISSUE THREAD

**Issue by myroslav** [openprocurement/openprocurement.bot.identification#33]
Для забезпечення сумісності інших систем (публічного порталу, майданчиків, кабінетів органа оскарження, BI, Dozorro, etc.) з різними форматам довідок, які будуть видаватися ботом ідентифікації потрібно серед метаінформації (#36) про довідку додати атрибут `version` Який буде містити версію формату. Пропонується всі версії, що будуть ламати зворотню сумісність (наприклад видалення елемента, перейменування, переміщення) формувати в MAJOR версії, всі зміни, які будуть забезпечувати зворотню сумісність (додавання додаткових атрибутів) формувати за допомогою MINOR версії, інші зміни, що не змінюють об'єм чи атрибути інформації, але виправляють помилки - в BUGFIX версії.

**Comment by Mexicanec** [comment]
@myroslav Мирослав, ты предлагаешь поддерживать версионность формата справки, или версионность самой справки? Я так понимаю, что первое. Но насколько часто будет меняться/меняется этот формат? Если формат предполагает изменяемость, то я согласен с твоим предложением.

**Comment by myroslav** [comment]
Версійність формата довідки.

Версійність самої довідки вже забезпечується openprocurement.api, але bot поки що не вміє оформляти кількох версій довідки. Це потенційно може бути потрібним, коли довідка буде мати строк придатності, і якщо bot буде зобов'язаний поновлювати таку довідку свіжішою версією. Але це не є питанням цього Issue, і має бути віришене на рівні ТЗ.

Зараз питання про те, що потрібно додати версію формату довідки в файл самої довідки і чим скорше тим краще, через те, що після того, як ми поміняємо щось у форматі, а можливості визначити версію не буде, то нас користувачі (розробники публічного порталу, та майданчиків) з'їдять з "потрохами"...
