### ISSUE TITLE
Невідповідна довідка

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#46]
`https://lb.api-sandbox.openprocurement.org/api/dev/tenders/bdd0161c1bbd4a3e91fbd36144df1192`
В qualification 78550c4342fb4a618591f36fede81fd3 додано 2 довідки і вони не відповідають коду учасника.

**Comment by IrynaPomazan** [comment]
Даний ЄДРПОУ на пісочниці ЄДР API на перший запит повертає список з двох елементів, для кожного з них створено файл. Дані в файлах відповідають даним, які надійшли від  ЄДР API. Бачу помилку в даних, а саме, для x_edrInternalId - 20807213 в полі founders замість id = 20807216 мало б бути 20807213. Але саме такі дані ми отримали від ЄДР API. Поле founders.id це унікальний ідентифікатор суб'єкта(x_edrInternalId).  Чи про інший код іде мова?

**Comment by kroman0** [comment]
bidID: e5c4c32889be4244a447ed580e5ef723
Його код 04593340, але в довідках 00022527 і 22883141, хоча проксі віддає 04593340

**Comment by IrynaPomazan** [comment]
Для даного e5c4c32889be4244a447ed580e5ef723 в обох файлах поле identification.id = 04593340. Значення  00022527 і 22883141 це значення поля founders.code. З документації ЄДР API поле founders.code: ЄДРПОУ код, якщо суб'єкт - юр.особа (тобто  ЄДРПОУ засновника мабуть).

**Comment by kroman0** [comment]
Тоді все ок.
