### ISSUE TITLE
Coverage 90%

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#6]

**Comment by kroman0** [comment]
https://coveralls.io/builds/10783018/source?filename=openprocurement%2Fbot%2Fidentification%2Fdatabridge%2Fupload_file.py#L60
https://coveralls.io/builds/10783018/source?filename=openprocurement%2Fbot%2Fidentification%2Fdatabridge%2Fupload_file.py#L95
https://coveralls.io/builds/10783018/source?filename=openprocurement%2Fbot%2Fidentification%2Fdatabridge%2Fupload_file.py#L162
https://coveralls.io/builds/10783018/source?filename=openprocurement%2Fbot%2Fidentification%2Fdatabridge%2Fedr_handler.py#L109
https://coveralls.io/builds/10783018/source?filename=openprocurement%2Fbot%2Fidentification%2Fdatabridge%2Fedr_handler.py#L195

**Comment by Krokop** [comment]
Питання ще актуальне?
