### ISSUE TITLE
Недопущення появи exception

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#7]
якщо код справді працює як передбачено
https://github.com/openprocurement/openprocurement.bot.identification/pull/4#discussion_r106132580

**Comment by Krokop** [comment]
Це issue можно закрити?

**Comment by myroslav** [comment]
Ця проблема ще не вирішена. В https://github.com/openprocurement/openprocurement.bot.identification/pull/4#discussion_r107376624 виписано, що прийняли #4 з умовою, що exception не будуть "вилітиати" при тестуванні, відповідно оформили цей Issue. Тому output має бути "чистим", а він таким поки що не є. Якщо є, то дайте посилання на приклад "чистого" логу тестування `master` гілки на travis-ci.org, і ми закриємо цей Issue.
