### ISSUE TITLE
Залипло завантаження довідок в тендер

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#73]
https://lb.api-sandbox.openprocurement.org/api/dev/tenders/d75db071f8244099868c763741ee16f1/awards/4b5c942c00a04af5aac191f909bab816/documents
https://lb.api-sandbox.openprocurement.org/api/2.3/tenders/42de4fc13ba046f0be9e6fa24e7642f8/qualifications/eb1b4e7c06e044239d5cf4fcd2ac9749/documents

**Comment by ZVasyl** [comment]
@Mexicanec , please comment on bug criticality.

**Comment by myroslav** [comment]
Я додав `major` так як вважаю цей issue критичним. @Mexicanec забери, якщо вважаєш по іншому.

Якщо bot "залипне" так як описано в цьому issue, то в ЦБД будуть завантажені сотні ідентичних довідок.

Припинити це може ручний рестарт bot-а. Відповідно цей issue в продуктиві зобов'яже моніторити 24х7 його поведінку з допомогою спеціальних інстрментів. Крім того реакція post-factum залишатиме багато довідок в ЦБД і потребуватиме додаткових зусиль щодо комунікування причин майданчикам, замовникам, постачальникам, політикам.
