### ISSUE TITLE
Уникнення помилок при тестуванні

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#9]
https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/214594422#L194

**Comment by Krokop** [comment]
Стосовно traceback в тестах: вони з’являються в stdout в результаті навмисного виклику помилки  (наприклад передача невірного формату даних), що є очікуваною поведінкою.

**Comment by kroman0** [comment]
https://travis-ci.org/openprocurement/openprocurement.bot.identification#L182

**Comment by kroman0** [comment]
#39 #38
